name: run-github-stats-checkpoint

on:
  workflow_dispatch:
  
jobs:
  great_expectations_validation:
    runs-on: ubuntu-latest
    steps:
    - name: Install python
      uses: actions/setup-python@v3
 
    - name: Copy Repository contents
      uses: actions/checkout@main 
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
 
    - name: Run Checkpoint
      run: |
        replace_webhook=$(printf '%s\n' ${{ secrets.VALIDATION_NOTIFICATION_SLACK_WEBHOOK }} | sed -e 's/[\/&]/\\&/g')
        sed -i "s/SECRET_SLACK_WEBHOOK/$replace_webhook/g" great_expectations/checkpoints/github_stats_checkpoint.yml
        
        python great_expectations/checkpoints/run_github_stats_checkpoint.py